sonar.projectKey=agh
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/*.test.js
sonar.host.url=http://localhost:9000
sonar.language=ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.token=sqp_7d82a4d43b0cfd4b0ea9467052ee8eb1619c8b7c